In [8]:
import math
import warnings

from IPython.display import display
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn import linear_model
import statsmodels.formula.api as smf

# Display preferences.
%matplotlib inline
pd.options.display.float_format = '{:.3f}'.format

# Suppress annoying harmless error.
warnings.filterwarnings(
    action="ignore",
    module="scipy",
    message="^internal gelsd"
)

In [70]:
df = pd.read_excel('table_8_offenses_known_to_law_enforcement_new_york_by_city_2013.xls')
df.columns = df.iloc[3]
df = df.drop([0,1,2,3])
df['Murder'] = df['Murder and\nnonnegligent\nmanslaughter']
df = df.dropna(subset=['Population', 'Robbery', 'Murder'])
df.head()

3,City,Population,Violent crime,Murder and nonnegligent manslaughter,Rape (revised definition)1,Rape (legacy definition)2,Robbery,Aggravated assault,Property crime,Burglary,Larceny- theft,Motor vehicle theft,Arson3,Murder
4,Adams Village,1861,0,0,NaN,0,0,0,12,2,10,0,0,0
5,Addison Town and Village,2577,3,0,NaN,0,0,3,24,3,20,1,0,0
6,Akron Village,2846,3,0,NaN,0,0,3,16,1,15,0,0,0
7,Albany,97956,791,8,NaN,30,227,526,4090,705,3243,142,NaN,8
8,Albion Village,6388,23,0,NaN,3,4,16,223,53,165,5,NaN,0

In [71]:
df['Population2'] = df['Population'] * df['Population']
def categor(df) :
    if int(df['Murder']) > 0 or int(df['Robbery']) > 1:
        return 1
    else:
        return 0
df['Murder'] = df.apply(lambda df:categor(df) ,axis = 1)

df['Robbery'] = df.apply(lambda df:categor(df) ,axis = 1)

In [81]:
regr = linear_model.LinearRegression()
Y = df['Property\ncrime'].values.reshape(-1, 1)
X = df[['Population','Population2','Murder', 'Robbery']]
regr.fit(X, Y)

# Inspect the results.
print('\nCoefficients: \n', regr.coef_)
print('\nIntercept: \n', regr.intercept_)
print('\nR-squared:')
print(regr.score(X, Y))

Coefficients:
 [[ 3.50962794e-02 -2.16275699e-09 -5.84663042e+01 -5.84663042e+01]]

Intercept:
 [-118.90025468]

R-squared:
0.9961389481949947